### PR TITLE
Identify versions

### PR DESCRIPTION
**Pull request by MarcioMateus**
Branch created to start addressing https://github.com/crossminer/scava/issues/75

This relates the commit ID with the software used in for deployment.
It creates a file on the root of the filesystem of the docker image `version` with the structure: `<branch:commitID>`

To get the current version of each docker image run: `docker-compose -f docker-compose-build.yml up`

The expected result is: 
```
docker-compose -f docker-compose-versions.yml up
Recreating scava-deployment_oss-app_1      ... done
Recreating scava-deployment_api-server_1   ... done
Starting scava-deployment_dashb-importer_1 ... done
Recreating scava-deployment_kb-service_1   ... done
Recreating scava-deployment_auth-server_1  ... done
Recreating scava-deployment_admin-webapp_1 ... done
Attaching to scava-deployment_auth-server_1, scava-deployment_dashb-importer_1, scava-deployment_oss-app_1, scava-deployment_admin-webapp_1, scava-deployment_api-server_1, scava-deployment_kb-service_1
auth-server_1     | dev-03efd3830e7d3c223d5b51e450346b828e953dba
oss-app_1         | dev-03efd3830e7d3c223d5b51e450346b828e953dba
dashb-importer_1  | dev-88dbcf4f231765dd2b8ff4ac63dfb31be1d1068d
admin-webapp_1    | dev-88dbcf4f231765dd2b8ff4ac63dfb31be1d1068d
api-server_1      | dev-03efd3830e7d3c223d5b51e450346b828e953dba
kb-service_1      | dev-03efd3830e7d3c223d5b51e450346b828e953dba
scava-deployment_auth-server_1 exited with code 0
scava-deployment_dashb-importer_1 exited with code 0
scava-deployment_oss-app_1 exited with code 0
scava-deployment_api-server_1 exited with code 0
scava-deployment_admin-webapp_1 exited with code 0
scava-deployment_kb-service_1 exited with code 0
```

To support the selection of the branch of SCAVA used on the deployment, an `.env` file was created to identify the branch used during the building of the containers. You can define the branch of individual Docker images either by modifying the docker-compose file e.g:
```
    oss-app:
        build:
          context: ./metric-platform
          args:
            - BRANCH=my-branch
```
or by modifying the value of `ARG BRANCH` on the corresponding Dockerfile.

I also did some optimisations to size of the images, let me know if you see any unexpected behaviour.

I invite everyone interested to test these new features and to provide feedback.

### CODE REVIEW

**Comment by mhow2** [comment]
@MarcioMateus, @ambpro , I have an issue with the admin-ui on my side:

```
(...)
+ @angular-devkit/build-angular@0.6.8
updated 1 package and audited 47884 packages in 12.204s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Your global Angular CLI version (7.3.9) is greater than your local
version (6.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
                                                                                     
Date: 2019-09-20T10:40:18.973Z
Hash: 9e150114c28ce3c25371
Time: 12646ms
chunk {scripts} scripts.e4a40f9a67a8eeb33234.js (scripts) 239 kB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.65c94c559c1e7e144a1d.css (styles) 304 kB [initial] [rendered]
chunk {2} polyfills.e7f5364b276024e19b0b.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.0594610c91de797f492a.js (main) 128 bytes [initial] [rendered]

ERROR in src/app/layout/project/components/edit-project/delete-connector/delete-connector-dialog.component.html(1,25): : Property 'sourceInfo' does not exist on type 'ConnectorMgmtDeleteDialogComponent'.
src/app/layout/project/components/edit-project/delete-connector/delete-connector-dialog.component.html(1,25): : Property 'target' does not exist on type 'ConnectorMgmtDeleteDialogComponent'.
src/app/layout/project/components/edit-project/delete-connector/delete-connector-dialog.component.html(1,25): : Property 'project' does not exist on type 'ConnectorMgmtDeleteDialogComponent'. Did you mean 'projectId'?
src/app/layout/project/components/edit-project/add-connector/add-connector-dialog.component.html(1,22): : Property 'sourceInfo' does not exist on type 'ConnectorMgmtAddDialogComponent'.
src/app/layout/project/components/edit-project/add-connector/add-connector-dialog.component.html(1,22): : Property 'project' does not exist on type 'ConnectorMgmtAddDialogComponent'.

ERROR: Service 'admin-webapp' failed to build: The command '/bin/sh -c echo "$BRANCH-$(git ls-remote https://github.com/crossminer/scava.git $BRANCH | awk '{ print $1}')" > version &&  svn export https://github.com/crossminer/scava/branches/$BRANCH/administration/scava-administration/ &&  cd scava-administration &&  npm update &&  npm install &&  npm install -g @angular/cli@7.3.9 &&  npm install --save-dev @angular-devkit/build-angular &&  ng build --prod' returned a non-zero code: 1
```

**Comment by MarcioMateus** [comment]
I am also getting that error. I seems to be introduced with the adding of the feature edit the connectors of a project. 

@ambpro can you give it a new check? Can it be related with the versions of the software in building stack?
In the Docker image am using `Nodejs 8.16.1` and running  the commands `npm install -g  angular/cli@7.3.9` and `npm install --save-dev @angular-devkit/build-angular@0.7.3`.

Are you using different versions on your environment?

**Comment by ambpro** [comment]
Well, as you said before @MarcioMateus, the problem is related to the connectors management feature. I pushed two fixes (https://github.com/crossminer/scava/commit/af7bb5ca254095951485892a24a6654512531416 and https://github.com/crossminer/scava/commit/141384d91d4be45fdc00a4cc6d90dda4ebc569e0) to remove the useless args in call methods.
I also re-tested it again and it works.

**Comment by MarcioMateus** [comment]
I confirm that it is also working on my side.

**Pull request merged**
